### ISSUE TITLE
issue/User and Summoner model design

### ISSUE THREAD

**Issue by mieseung** [swsnu/swpp2021-team3#13]
몇 가지 정하고 공유해야할 이슈들이 있어서 공유합니다!

1. 지금 User model과 Summoner model이 one to one 관계인데, Summoner가 사라졌을 때 User model에서 어떻게 대처할지 정해야할 것 같습니다. (`on_delete`) 선택지가 크게 두 가지가 있을 것 같은데, 
    - `DESCADE` : summoner가 사라졌을 때 User가 가리키고 있는 summoner row가 사라지면서 같이 user도 사라지는 방식입니다. 롤 탈퇴 (계정 폭파) = 우리 서비스 탈퇴를 의미하게 되는 거라, 조금 극단적인 처리일 수 있습니다. 대신, Summoner가 사라진 이후에 리포트를 보내는 등 user에 summoner가 연결되어 있어야만 할 수 있는 활동에 대한 exception 처리를 줄일 수 있습니다. 롤 탈퇴를 하면 그 summoner로 리포트 할 일은 없을 거기 때문에 자연스러운 것 같기도 합니다.
    - `SET_NULL` : summoner가 사라졌을 때 User에 summoner field를 `null`로 변경하는 방식입니다. Summoner가 사라져도 가입한 User가 사라지지 않아, 유저 입장에서 뜬금없이 유저가 삭제되는 현상은 방지할 수 있습니다. 대신, Summoner가 사라진 이후에 리포트를 보내려고 한다면, Summoner를 다시 등록하거나 아니면 재회원가입을 하라는 신호를 보내야할 것 같습니다. 사실 롤 탈퇴가 흔한 일도 아니고, 롤 탈퇴를 했을 때는 당연히 리포트할 일도 없기 때문에 제가 보기엔 `SET_NULL`도 괜찮은 것 같습니다.

    장단점이 확실한데 혹시 둘 중에 어떤 게 좋을 것 같은지 의견 주세요!

2. Riot api로 가져오는 계정 정보들 중에 summoner를 구별할 수 있는 정보가 몇 가지 있는 것 같습니다. 
![image](https://user-images.githubusercontent.com/55074514/139561597-9fa95cb0-5f24-493b-a69e-d59855dfb45a.png)
이것들 중에 puuid가 user를 구별할 수 있으면서도 대부분의 api에서 많이 쓰여서, Summoner 모델에 사용하는 summoner_id는 puuid로 하려고 합니다.

지금까지 생각난 것들은 이정도 있을 것 같은데, 보시고 의견 주시면 감사하겠습니당 :)

**Comment by Junetrbl** [comment]
저는 개인적으로는 descade 방법이 맞는 것 같아요. 2번 내용은 숙지했습니다. 이와 별개로 대부분의 유저가 부계정을 파곤 하는데 이부분에대한 고려는 없어도될까요?

**Comment by mieseung** [comment]
> 저는 개인적으로는 descade 방법이 맞는 것 같아요. 2번 내용은 숙지했습니다. 이와 별개로 대부분의 유저가 부계정을 파곤 하는데 이부분에대한 고려는 없어도될까요?

어차피 부계정이면 다른 summoner인 거니까 괜찮을 것 같아요!

**Comment by Xena123kiki** [comment]
저도 윤수님 말씀처럼 Descade가 좋을 것 같습니다! 계정 폭파를 하는 경우에 가장 자연스러운 방법이라고 생각합니다. 중요한 고민 공유해주셔서 정말 감사합니다.
